-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(C.SALES * A.PRICE) as TOTAL_SALES
from BOOK as A
inner join AUTHOR as B
on A.AUTHOR_ID = B.AUTHOR_ID
inner join BOOK_SALES as C
on A.BOOK_ID = C.BOOK_ID
where C.SALES_DATE like '2022-01%'
group by A.AUTHOR_ID, A.CATEGORY
order by A.AUTHOR_ID, A.CATEGORY desc;